# Generated by Django 5.0.3 on 2024-03-30 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_note_body_alter_note_title_alter_team_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='user_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='team_notes', to='api.note'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='team_user', to='api.team'),
        ),
    ]
